baseurl:     "" 
claim:       "Proposta per una metafisica open-source" 
destination: docs/
highlighter: none
keyword:    "C'hi, C++, c plus plus, religione, open-source"    
og_desc:    "Chi++ - Proposta per una metafisica open-source"
og_img_h:   "630"
og_img_w:   "1200"
og_img:     "/assets/img/chi-plus-plus.jpg"
title:       "C'hi++"
url:         "https://chiplusplus.org" 

exclude: [
    'src'
  , 'bin' 
  , 'CHANGELOG'
  , 'CONTRIBUTING.md'
  , 'MANIFEST.md'
  , 'README.md'
  , 'TODO'
  , 'VERSION'
  , 'assets/img/og-img/og-image.psd'
]

sass:
    style: compressed

collections:
    man:
        output: true
        order:
            - copertina.md
            - dedica.md
            - indice.md
            - prologo.md
            - incipit.md
            - mitopoietica.md
            - programmatore.md
            - sistemi-di-numerazione.md
            - linguaggi-di-programmazione.md
            - c-plus-plus.md
            - commenti.md
            - tipi-di-dato.md
            - struttura-dei-programmi.md
            - operatori.md
            - preprocessore.md
            - memoria.md
            - funzioni.md
            - istruzioni-condizionali.md
            - istruzioni-iterative.md
            - classi-oggetti.md
            - ereditarieta.md
            - polimorfismo.md
            - stream.md
            - debug.md
            - epilogo.md
            - ringraziamenti.md
            - bibliografia.md
