baseurl: "" 
url:     "https://chiplusplus.org" 
title:   "C'hi++"
claim:   "Proposta per una metafisica open-source" 
destination: docs/
highlighter: none
exclude: [
    bin
  , src
  , CHANGELOG
  , CONTRIBUTING.md
  , MANIFEST.md
  , README.md
  , TODO
  , VERSION
]
sass:
  style: compressed
collections:
   man:
      output: true
      order:
         - copertina.md
         - dedica.md
         - indice.md
         - prologo.md
         - incipit.md
         - mitopoietica.md
         - il-programmatore.md
         - sistemi-di-numerazione.md
         - linguaggi-di-programmazione.md
         - c-plus-plus.md
         - commenti.md
         - tipi-di-dato.md
         - espressioni-e-operatori.md
         - funzioni.md
         - classi.md
         - polimorfismo.md
         - ereditarieta.md
         - debug.md
         - chi-plus-plus.md
         - spazionismo.md
         - ikebarba.md
         - epilogo.md
         - poesia-funeraria.md
