baseurl: ""
claim: "Proposta per una metafisica open-source"
destination: docs/
highlighter: none
keyword: "C'hi, C++, c plus plus, religione, open-source"
og_desc: "Chi++ - Proposta per una metafisica open-source"
og_img_h: "630"
og_img_w: "1200"
og_img: "/assets/img/og-img/indice.jpg"
title: "C'hi++"
url: "https://chiplusplus.org"
url_github: "https://github.com/TacunIT/chi-plus-plus"

exclude:
  [
    "src",
    "bin",
    "_man/_it/src",
    "_man/_en/src",
    "CHANGELOG",
    "CONTRIBUTING.md",
    "MANIFEST.md",
    "README.md",
    "TODO",
    "VERSION",
    "assets/img/og-img/og-image.psd",
    "presentazione.md",
  ]

sass:
  style: compressed

collections_dir: _man

collections:
  it:
    output: true
    order:
      - 01.copertina.md
      - 02.dedica.md
      - 03.indice.md
      - 04.introduzione.md
      - 05.prologo.md
      - 06.incipit.md
      - 07.mitopoietica.md
      - 08.programmatore.md
      - 09.sistemi-di-numerazione.md
      - 10.linguaggi-di-programmazione.md
      - 11.c-plus-plus.md
      - 12.commenti.md
      - 13.tipi-di-dato.md
      - 14.struttura-dei-programmi.md
      - 15.operatori.md
      - 16.preprocessore.md
      - 17.memoria.md
      - 18.funzioni.md
      - 19.istruzioni-condizionali.md
      - 20.istruzioni-iterative.md
      - 21.classi-oggetti.md
      - 22.ereditarieta.md
      - 23.polimorfismo.md
      - 24.stream.md
      - 25.debug.md
      - 26.epilogo.md
      - 27.note.md
      - 28.ringraziamenti.md
      - 29.bibliografia.md
  en:
    output: true
    order:
      - 01.cover.md
      - 02.dedication.md
      - 03.index.md
      - 04.introduction.md
      - 05.prologue.md
      - 06.incipit.md
      - 07.mythopoetics.md
      - 08.programmer.md
      - 09.numeral-systems.md
      - 10.programming-languages.md
      - 11.c-plus-plus.md
      - 12.comments.md
      - 13.data-types.md
      - 14.program-structure.md
      - 15.operators.md
      - 16.preprocessore.md
      - 17.memory.md
      - 18.functions.md
      - 19.conditional-instructions.md
      - 20.iterative-instructions.md
      - 21.classes-objects.md
      - 22.inheritance.md
      - 23.polymorphism.md
      - 24.stream.md
      - 25.debug.md
      - 26.epilogue.md
      - 27.notes.md
      - 28.acknowledgments.md
      - 29.bibliography.md
