baseurl: ""
claim: "Proposta per una metafisica open-source"
destination: docs/
highlighter: none
keyword: "C'hi, C++, c plus plus, religione, open-source"
og_desc: "Chi++ - Proposta per una metafisica open-source"
og_img_h: "630"
og_img_w: "1200"
og_img: "/assets/img/og-img/indice.jpg"
title: "C'hi++"
url: "https://chiplusplus.org"
url_github: "https://github.com/TacunIT/chi-plus-plus"

exclude:
  [
    "src",
    "bin",
    "_man/_it/src",
    "_man/_en/src",
    "CHANGELOG",
    "CONTRIBUTING.md",
    "MANIFEST.md",
    "README.md",
    "TODO",
    "VERSION",
    "assets/img/og-img/og-image.psd",
    "presentazione.md",
  ]

sass:
  style: compressed

collections_dir: _man

collections:
  it:
    output: true
    order:
      - 01.copertina.md
      - 02.dedica.md
      - 03.indice.md
      - 04.introduzione.md
      - 05.prologo.md
      - 06.incipit.md
      - 07.mitopoietica.md
      - 08.programmatore.md
      - 09.sistemi-di-numerazione.md
      - 10.linguaggi-di-programmazione.md
      - c-plus-plus.md
      - commenti.md
      - tipi-di-dato.md
      - struttura-dei-programmi.md
      - operatori.md
      - preprocessore.md
      - memoria.md
      - funzioni.md
      - istruzioni-condizionali.md
      - istruzioni-iterative.md
      - classi-oggetti.md
      - ereditarieta.md
      - polimorfismo.md
      - stream.md
      - debug.md
      - epilogo.md
      - note.md
      - ringraziamenti.md
      - bibliografia.md
  en:
    output: true
    order:
      - 01.copertina.md
      - 02.dedica.md
      - 03.indice.md
      - 04.introduzione.md
      - 05.prologo.md
      - 06.incipit.md
      - 07.mitopoietica.md
      - 08.programmatore.md
      - 09.sistemi-di-numerazione.md
      - 10.linguaggi-di-programmazione.md
      - c-plus-plus.md
      - commenti.md
      - tipi-di-dato.md
      - struttura-dei-programmi.md
      - operatori.md
      - preprocessore.md
      - memoria.md
      - funzioni.md
      - istruzioni-condizionali.md
      - istruzioni-iterative.md
      - classi-oggetti.md
      - ereditarieta.md
      - polimorfismo.md
      - stream.md
      - debug.md
      - epilogo.md
      - note.md
      - ringraziamenti.md
      - bibliografia.md
