baseurl: "" 
url: "https://chiplusplus.org" 
title: "C'hi++ - Proposta per una metafisica open-source" 
exclude: [CHANGELOG, CONTRIBUTING.md, MANIFEST.md, README.md, TODO, VERSION]
destination: docs/
disable_disk_cache: true