url: "https://chiplusplus.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "C'hi++ - Il senso della vita è il debug" # the name of your site, e.g. ACME Corp.
destination: ../docs
